#!/usr/bin/env python3
"""
Groth16 Trusted Setup Implementation
=====================================

Implements circuit-specific trusted setup for Groth16.

WARNING: This is a SINGLE-PARTY setup suitable for development and testing.
Production deployments require a Multi-Party Computation (MPC) ceremony to ensure
no single party possesses the toxic waste (α, β, γ, δ, τ).

The cryptographic operations are REAL and correct. The limitation is that toxic
waste is generated by one party, which must be trusted to destroy it properly.

Based on GROTH16_IMPLEMENTATION.md Section 3 and production_zkp_fl_complete.py standards.

Author: ZKP-FL Framework
Version: 1.0.0
"""

import logging
import hashlib
import json
from typing import Dict, List, Tuple, Any, Optional
from dataclasses import dataclass
import secrets

# BN128 curve operations (same as Protostar)
# CRITICAL: Use py_ecc.bn128 for ALL types to avoid incompatibility
# bn128.FQ2 and optimized_bn128.FQ2 are DIFFERENT classes!
from py_ecc.bn128 import (
    G1, G2, multiply, add, pairing, curve_order, FQ, FQ2
)

from .r1cs import R1CS
from .qap import QAP

logger = logging.getLogger(__name__)


@dataclass
class ProvingKey:
    """
    Groth16 Proving Key (pk) - Libsnark specification
    
    Following libsnark/bellman/arkworks standard implementation.
    See LIBSNARK_GROTH16_SPEC.md for details.
    """
    # Basic toxic waste elements
    alpha_G1: Tuple[FQ, FQ]           # [α]₁
    beta_G1: Tuple[FQ, FQ]            # [β]₁
    beta_G2: Tuple[FQ2, FQ2]          # [β]₂
    delta_G1: Tuple[FQ, FQ]           # [δ]₁
    delta_G2: Tuple[FQ2, FQ2]         # [δ]₂
    
    # QAP polynomial evaluations
    # [Aᵢ(τ)]₁ for all variables i ∈ {0...m}
    A_query: List[Tuple[FQ, FQ]]
    
    # [Bᵢ(τ)]₁ for all variables (needed for π_C computation)
    B_query_G1: List[Tuple[FQ, FQ]]
    
    # [Bᵢ(τ)]₂ for all variables (needed for π_B)
    B_query_G2: List[Tuple[FQ2, FQ2]]
    
    # [(βAᵢ(τ) + αBᵢ(τ) + Cᵢ(τ))/δ]₁ for PRIVATE witness only (i ∈ {l+1...m})
    # l = number of public inputs (includes constant 1)
    L_query: List[Tuple[FQ, FQ]]
    
    # [τⁱ/δ]₁ for i ∈ {0...degree(h)}
    # Used for computing quotient polynomial h(τ)/δ
    H_query: List[Tuple[FQ, FQ]]
    
    # Circuit metadata
    num_variables: int
    num_constraints: int
    num_public_inputs: int  # Includes constant 1


@dataclass
class VerificationKey:
    """
    Groth16 Verification Key (vk) - Libsnark specification
    
    Following libsnark/bellman/arkworks standard implementation.
    See LIBSNARK_GROTH16_SPEC.md for details.
    """
    alpha_G1: Tuple[FQ, FQ]           # [α]₁
    beta_G2: Tuple[FQ2, FQ2]          # [β]₂
    gamma_G2: Tuple[FQ2, FQ2]         # [γ]₂
    delta_G2: Tuple[FQ2, FQ2]         # [δ]₂
    
    # IC query: [(βAᵢ(τ) + αBᵢ(τ) + Cᵢ(τ))/γ]₁ for PUBLIC inputs
    # IC[0] for constant 1, IC[1...l] for actual public inputs
    # Length = num_public_inputs + 1
    IC_query: List[Tuple[FQ, FQ]]


class Groth16TrustedSetup:
    """
    Groth16 Trusted Setup Generator
    
    CRITICAL: This is a DEVELOPMENT setup only.
    Production requires secure Multi-Party Computation (MPC) ceremony.
    
    Standard from GROTH16_IMPLEMENTATION.md Section 3
    """
    
    def __init__(self, r1cs: R1CS):
        """
        Initialize setup with R1CS
        
        Args:
            r1cs: Complete R1CS constraint system
        """
        self.r1cs = r1cs
        self.num_variables = r1cs.num_variables
        self.num_constraints = r1cs.num_constraints
        self.num_public_inputs = len(r1cs.public_input_indices)
        
        # Build QAP from R1CS
        self.qap = QAP(r1cs.A, r1cs.B, r1cs.C, r1cs.num_variables)
        self.qap.construct_polynomials()
        
        logger.info(f"Initializing Groth16 trusted setup:")
        logger.info(f"  Variables: {self.num_variables}")
        logger.info(f"  Constraints: {self.num_constraints}")
        logger.info(f"  Public inputs: {self.num_public_inputs}")
        logger.info(f"  QAP degree: {len(self.qap.t_poly) - 1}")
    
    def generate_toxic_waste(self, seed: Optional[bytes] = None) -> Dict[str, int]:
        """
        Generate toxic waste parameters (α, β, γ, δ, τ)
        
        WARNING: These must be destroyed after setup!
        In production, use secure MPC ceremony.
        
        From GROTH16_IMPLEMENTATION.md Section 3.1
        """
        def generate_random_field_element() -> int:
            """Generate cryptographically secure random field element"""
            # Use secrets module for cryptographic randomness
            # Generate random bytes and mod into field
            random_bytes = secrets.token_bytes(64)  # 512 bits for good randomness
            random_int = int.from_bytes(random_bytes, 'big')
            return random_int % curve_order
        
        if seed is not None:
            # Deterministic mode for testing/debugging only
            logger.warning("⚠️  Using DETERMINISTIC toxic waste from seed - NOT SECURE")
            def derive_field_element(label: str) -> int:
                h = hashlib.sha256(seed + label.encode()).digest()
                return int.from_bytes(h, 'big') % curve_order
            
            toxic_waste = {
                'alpha': derive_field_element('alpha'),
                'beta': derive_field_element('beta'),
                'gamma': derive_field_element('gamma'),
                'delta': derive_field_element('delta'),
                'tau': derive_field_element('tau')
            }
        else:
            # Cryptographically secure random generation
            toxic_waste = {
                'alpha': generate_random_field_element(),
                'beta': generate_random_field_element(),
                'gamma': generate_random_field_element(),
                'delta': generate_random_field_element(),
                'tau': generate_random_field_element()
            }
        
        logger.warning("⚠️  TOXIC WASTE GENERATED - MUST DESTROY AFTER SETUP")
        logger.info("   In production, use Multi-Party Computation (MPC) ceremony")
        
        return toxic_waste
    
    def generate_keys(self, seed: Optional[bytes] = None) -> Tuple[ProvingKey, VerificationKey]:
        """
        Generate proving key and verification key
        
        From GROTH16_IMPLEMENTATION.md Section 3.2-3.3
        """
        logger.info("🔑 Generating Groth16 keys...")
        
        # Step 1: Generate toxic waste
        toxic = self.generate_toxic_waste(seed)
        alpha, beta, gamma, delta, tau = (
            toxic['alpha'], toxic['beta'], toxic['gamma'],
            toxic['delta'], toxic['tau']
        )
        
        # Step 2: Compute group elements
        alpha_G1 = multiply(G1, alpha)
        beta_G1 = multiply(G1, beta)
        beta_G2 = multiply(G2, beta)
        gamma_G2 = multiply(G2, gamma)
        delta_G1 = multiply(G1, delta)
        delta_G2 = multiply(G2, delta)
        
        # Step 3: Evaluate QAP polynomials at τ
        A_at_tau, B_at_tau, C_at_tau = self._evaluate_r1cs_at_tau(tau)
        
        # Step 4: Generate A, B, C query terms
        # [Aᵢ(τ)]₁, [Bᵢ(τ)]₁, [Bᵢ(τ)]₂ for ALL variables
        A_query = [multiply(G1, a_val) for a_val in A_at_tau]
        B_query_G1 = [multiply(G1, b_val) for b_val in B_at_tau]
        B_query_G2 = [multiply(G2, b_val) for b_val in B_at_tau]
        
        # Step 5: Generate L-query for PRIVATE witness only
        # L_query[i] = [(βAᵢ(τ) + αBᵢ(τ) + Cᵢ(τ))/δ]₁ for i ∈ {l+1...m}
        # where l = num_public_inputs (includes constant 1)
        delta_inv = pow(delta, -1, curve_order)
        L_query = []
        
        # Get indices of private witness variables
        # public_input_indices includes 0 (constant), so private starts after last public
        private_start_idx = max(self.r1cs.public_input_indices) + 1
        
        for idx in range(private_start_idx, self.num_variables):
            L_val = (
                beta * A_at_tau[idx] +
                alpha * B_at_tau[idx] +
                C_at_tau[idx]
            ) % curve_order
            L_val = (L_val * delta_inv) % curve_order
            L_query.append(multiply(G1, L_val))
        
        # Step 5: Generate H-query for quotient polynomial
        # H_query[i] = [τⁱ/δ]₁ for i ∈ {0...degree}
        # degree = num_constraints - 1 (degree of quotient h(x))
        H_query = []
        tau_power = 1
        for i in range(self.num_constraints):
            h_val = (tau_power * delta_inv) % curve_order
            H_query.append(multiply(G1, h_val))
            tau_power = (tau_power * tau) % curve_order
        
        # Step 6: Generate IC-query for PUBLIC inputs (for verification)
        # IC[i] = [(βAᵢ(τ) + αBᵢ(τ) + Cᵢ(τ))/γ]₁ for i ∈ public_input_indices
        gamma_inv = pow(gamma, -1, curve_order)
        IC_query = []
        
        for idx in self.r1cs.public_input_indices:
            IC_val = (
                beta * A_at_tau[idx] +
                alpha * B_at_tau[idx] +
                C_at_tau[idx]
            ) % curve_order
            IC_val = (IC_val * gamma_inv) % curve_order
            IC_point = multiply(G1, IC_val)  # Fixed: always use multiply, handles zero correctly
            IC_query.append(IC_point)
        
        # Build proving key
        proving_key = ProvingKey(
            alpha_G1=alpha_G1,
            beta_G1=beta_G1,
            beta_G2=beta_G2,
            delta_G1=delta_G1,
            delta_G2=delta_G2,
            A_query=A_query,
            B_query_G1=B_query_G1,
            B_query_G2=B_query_G2,
            L_query=L_query,
            H_query=H_query,
            num_variables=self.num_variables,
            num_constraints=self.num_constraints,
            num_public_inputs=self.num_public_inputs
        )
        
        # Build verification key
        verification_key = VerificationKey(
            alpha_G1=alpha_G1,
            beta_G2=beta_G2,
            gamma_G2=gamma_G2,
            delta_G2=delta_G2,
            IC_query=IC_query
        )
        
        logger.info(f"✅ Keys generated successfully")
        logger.info(f"   PK A_query: {len(A_query)} elements")
        logger.info(f"   PK B_query_G1: {len(B_query_G1)} elements")
        logger.info(f"   PK B_query_G2: {len(B_query_G2)} elements")
        logger.info(f"   PK L_query: {len(L_query)} elements (private witness)")
        logger.info(f"   PK H_query: {len(H_query)} elements")
        logger.info(f"   VK IC_query: {len(IC_query)} elements (public inputs)")
        logger.info(f"   Proving key size: ~{(len(A_query) + len(B_query_G1) + len(L_query) + len(H_query)) * 32} bytes")
        logger.info(f"   Verification key size: ~{len(IC_query) * 32 + 64*3} bytes")
        
        # CRITICAL: Securely destroy toxic waste
        self._destroy_toxic_waste(toxic)
        
        return proving_key, verification_key
    
    def _destroy_toxic_waste(self, toxic: Dict[str, int]):
        """
        Securely destroy toxic waste by overwriting with random data
        
        This is a best-effort approach. In production MPC, each party
        destroys their share independently.
        """
        # Overwrite each value with random data multiple times
        for key in toxic.keys():
            for _ in range(3):  # Overwrite 3 times
                toxic[key] = secrets.randbelow(curve_order)
        
        # Clear the dictionary
        toxic.clear()
        
        logger.info("🔒 Toxic waste securely destroyed")
    
    def _evaluate_r1cs_at_tau(self, tau: int) -> Tuple[List[int], List[int], List[int]]:
        """
        Evaluate QAP polynomials Aᵢ(τ), Bᵢ(τ), Cᵢ(τ) using proper Lagrange interpolation
        
        From GROTH16_IMPLEMENTATION.md Section 3.3
        
        Returns:
            A_at_tau, B_at_tau, C_at_tau for each variable
        """
        logger.info(f"Evaluating QAP polynomials at τ (secret point)...")
        
        # Use QAP's evaluate_at_tau method which does proper Lagrange interpolation
        A_at_tau, B_at_tau, C_at_tau = self.qap.evaluate_at_tau(tau)
        
        logger.info(f"✅ QAP polynomials evaluated:")
        logger.info(f"   A_at_tau: {len(A_at_tau)} values")
        logger.info(f"   B_at_tau: {len(B_at_tau)} values")
        logger.info(f"   C_at_tau: {len(C_at_tau)} values")
        
        return A_at_tau, B_at_tau, C_at_tau
    
    def export_proving_key(self, pk: ProvingKey, filepath: str):
        """Export proving key to file"""
        data = {
            'alpha_G1': self._serialize_G1(pk.alpha_G1),
            'beta_G1': self._serialize_G1(pk.beta_G1),
            'beta_G2': self._serialize_G2(pk.beta_G2),
            'delta_G1': self._serialize_G1(pk.delta_G1),
            'delta_G2': self._serialize_G2(pk.delta_G2),
            'tau_powers_G1': [self._serialize_G1(p) for p in pk.tau_powers_G1],
            'L_query': [self._serialize_G1(p) for p in pk.L_query],
            'H_query': [self._serialize_G1(p) for p in pk.H_query],
            'num_variables': pk.num_variables,
            'num_constraints': pk.num_constraints,
            'num_public_inputs': pk.num_public_inputs
        }
        
        with open(filepath, 'w') as f:
            json.dump(data, f, indent=2)
        
        logger.info(f"💾 Proving key exported to {filepath}")
    
    def export_verification_key(self, vk: VerificationKey, filepath: str):
        """Export verification key to file"""
        data = {
            'alpha_G1': self._serialize_G1(vk.alpha_G1),
            'beta_G2': self._serialize_G2(vk.beta_G2),
            'gamma_G2': self._serialize_G2(vk.gamma_G2),
            'delta_G2': self._serialize_G2(vk.delta_G2),
            'IC_query': [self._serialize_G1(p) for p in vk.IC_query]
        }
        
        with open(filepath, 'w') as f:
            json.dump(data, f, indent=2)
        
        logger.info(f"💾 Verification key exported to {filepath}")
    
    def _serialize_G1(self, point: Tuple[FQ, FQ]) -> List[str]:
        """Serialize G1 point to hex strings (affine coordinates)"""
        # py_ecc.bn128 uses affine coordinates (x, y), already normalized
        return [
            hex(int(point[0])),
            hex(int(point[1]))
        ]
    
    def _serialize_G2(self, point: Tuple[FQ2, FQ2]) -> List[List[str]]:
        """Serialize G2 point to hex strings (affine coordinates)"""
        # py_ecc.bn128 uses affine coordinates (x, y), already normalized
        return [
            [hex(int(point[0].coeffs[0])), hex(int(point[0].coeffs[1]))],
            [hex(int(point[1].coeffs[0])), hex(int(point[1].coeffs[1]))]
        ]


def generate_groth16_setup(r1cs: R1CS, seed: Optional[bytes] = None) -> Tuple[ProvingKey, VerificationKey, 'Groth16TrustedSetup']:
    """
    Convenience function to generate Groth16 setup
    
    Args:
        r1cs: Complete R1CS constraint system
        seed: Optional seed for deterministic generation
    
    Returns:
        (proving_key, verification_key, setup)
    """
    setup = Groth16TrustedSetup(r1cs)
    pk, vk = setup.generate_keys(seed)
    return pk, vk, setup
